server:
  port: 80
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
logging:
  level:
    org.springframework.security: DEBUG
springdoc:
  swagger-ui:
    enabled: true