server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://db:5432/products_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${JWT_SECRET}
logging:
  level:
    org.springframework.security: DEBUG
springdoc:
  swagger-ui:
    enabled: true