server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:productsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  secret: miClaveSecretaParaJwt12345678901
security:
  admin-user: admin
  admin-password: admin123
  admin-role: ADMIN
logging:
  level:
    org.springframework.security: DEBUG
springdoc:
  swagger-ui:
    enabled: true